// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDle27Lh_T7Yym_SoJwm_iNdMfTej9drxM',
    appId: '1:948116285912:web:933d12443d625c66f06aad',
    messagingSenderId: '948116285912',
    projectId: 'shopper-57485',
    authDomain: 'shopper-57485.firebaseapp.com',
    storageBucket: 'shopper-57485.appspot.com',
    measurementId: 'G-B504QR5JLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0I4F28G0tZdD5FbxnTlPxrITbLtfOovM',
    appId: '1:948116285912:android:79bd8927cb9bd21cf06aad',
    messagingSenderId: '948116285912',
    projectId: 'shopper-57485',
    storageBucket: 'shopper-57485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0RIwh3zTdI0QrrsZLZlp_78TeIHfQ8q0',
    appId: '1:948116285912:ios:8899d5f995129266f06aad',
    messagingSenderId: '948116285912',
    projectId: 'shopper-57485',
    storageBucket: 'shopper-57485.appspot.com',
    iosClientId: '948116285912-m8n9alcdksoeq36ma46clt6qibi5d94j.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.providerShopper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0RIwh3zTdI0QrrsZLZlp_78TeIHfQ8q0',
    appId: '1:948116285912:ios:8899d5f995129266f06aad',
    messagingSenderId: '948116285912',
    projectId: 'shopper-57485',
    storageBucket: 'shopper-57485.appspot.com',
    iosClientId: '948116285912-m8n9alcdksoeq36ma46clt6qibi5d94j.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.providerShopper',
  );
}
